const puppeteer = require('puppeteer-core');
const path = require('path');
const DIR = __dirname;
(async () => {
  const browser = await puppeteer.connect({ browserURL:'http://localhost:9222', defaultViewport:{width:1280,height:900} });
  const page = await browser.newPage();
  page.on('pageerror',e=>console.log('EXC:',e.message));
  await page.goto('file://'+path.join(DIR,'index.html')+'?test=1', {waitUntil:'networkidle0'});
  await (await page.$('#fileOld')).uploadFile(path.join(DIR,'test/sameA.pdf'));
  await (await page.$('#fileNew')).uploadFile(path.join(DIR,'test/sameB.pdf'));
  await page.evaluate(()=>{ document.getElementById('fileOld').dispatchEvent(new Event('change',{bubbles:true})); document.getElementById('fileNew').dispatchEvent(new Event('change',{bubbles:true})); });
  await new Promise(r=>setTimeout(r,2000));
  await page.click('#btnCompare');
  await new Promise(r=>setTimeout(r,6000));
  const r1 = await page.evaluate(async ()=>{ try{ document.getElementById('btnDownload').click(); await new Promise(r=>setTimeout(r,1500)); return 'lastPdf set: '+(window.__lastPdf?window.__lastPdf.length:'null'); }catch(e){ return 'ERR '+e.message; } });
  console.log('two-up:', r1);
  const r2 = await page.evaluate(async ()=>{ try{ document.getElementById('btnDownloadNew').click(); await new Promise(r=>setTimeout(r,1500)); return 'newOnly set: '+(window.__lastPdfNew?window.__lastPdfNew.length:'null'); }catch(e){ return 'ERR '+e.message; } });
  console.log('newOnly:', r2);
  await browser.disconnect();
})().catch(e=>{console.error('FATAL',e.message);process.exit(1);});
